### ISSUE TITLE
I genuinely can't figure out how to get this set up to try it out for myself

### ISSUE THREAD

**Issue by 0Daelin** [headshot2017/gzdoom-sm64#10]
I spent the last maybe 20-30 minutes digging through and trying to figure out what to do so I can just play the mod, but with no success. Can this potentially be explained a bit easier on the main page to be less confusing for caveman-brained people like me?

**Comment by headshot2017** [comment]
click on the [Actions](https://github.com/headshot2017/gzdoom-sm64/actions) tab on the top

next, click the first "workflow" that appears on the list, at the moment it's called "Mario lighting based on sector lightlevel" or something similar. if you see a gigantic wall of text (which just happened to me), scroll down and you'll see it, then click it

scroll down to "Artifacts", and click the one that says "gzdoom-sm64-release" to download the ZIP file

extract the ZIP file somewhere on your drive and go in there with your file explorer

get a mario64 US ROM, and place it in the gzdoom folder, with the file name "sm64.us.z64"

get a DOOM wad of your preference. you can try doom1, doom2, or if you want something for free, find a freedoom wad or a shareware doom wad online. put it in the gzdoom folder as well

launch gzdoom.exe and you should be good to go

i'll update the readme detailing these steps later today

**Comment by 0Daelin** [comment]
Thank you so much, you're an absolute lifesaver!
