### ISSUE TITLE
game crashes entirely now?

### ISSUE THREAD

**Issue by BinarryCode** [headshot2017/gzdoom-sm64#12]
I have a PC that can actually run this, in theory.

But it crashes on startup now.

I'm pretty sure this applies to every version but I can't really test it too well

**Comment by BinarryCode** [comment]
idk if its something with the pc specs but heres that
![image](https://user-images.githubusercontent.com/53833277/216727762-5ea82fc6-6976-40af-91bc-59de35553fcb.png)

**Comment by headshot2017** [comment]
drop your sm64 rom on this site just in case and see what the output is
[http://emn178.github.io/online-tools/sha1_checksum.html](http://emn178.github.io/online-tools/sha1_checksum.html)

**Comment by BinarryCode** [comment]
> drop your sm64 rom on this site just in case and see what the output is http://emn178.github.io/online-tools/sha1_checksum.html

its `9bef1128717f958171a4afac3ed78ee2bb4e86ce`, seems like the intended result according to sm64 decomp github.

**Comment by headshot2017** [comment]
try downloading and running unmodded gzdoom, both 3.2.0 and latest version to make sure it's not this mod causing the crashing

**Comment by BinarryCode** [comment]
I have 3.2.2, not sure if that's good enough but it runs fine (besides a rendering bug with opengl that fixed itself when I re-opened it)

**Comment by BinarryCode** [comment]
also the latest version seems to run fine as well

**Comment by headshot2017** [comment]
i downloaded the latest debug build and it seems to run fine - i can't seem to pinpoint what's going on. are you able to use MSYS2 or the GDB debugger? if you have either of these installed, that is

**Comment by BinarryCode** [comment]
I dont have either of them, at least not an updated version for the former

**Comment by headshot2017** [comment]
if it lets you, launch "MSYS2 MinGW x64" from your start menu and install gdb with `pacman -S mingw-w64-x86_64-gdb`.
if you don't have MSYS2 MinGW x64, go get it from their site

download the mod again but this time pick "gzdoom-sm64-debug". extract it to an empty folder.

in MSYS2, write "cd" followed by a space, then drag that new folder into the MSYS2 window, then hit enter.

type `gdb gzdoom.exe`, wait for GDB to load, then type "r" to run the game.

if GDB suddenly spits out "Segmentation fault", type `bt`, then share with me what GDB spits out, either via a screenshot or copy-pasting the contents

**Comment by BinarryCode** [comment]
Binar@DESKTOP UCRT64 /c/Users/Binar/Downloads/gzdoom-sm64-debug
$ gdb gzdoom.exe
-bash: gdb: command not found

I installed gdb

**Comment by headshot2017** [comment]
did you launch "MSYS2 MSYS" (purple icon) or "MSYS2 MinGW x64" (blue icon)? make sure you run gdb from within the latter.

also make sure you installed `mingw-w64-x86_64-gdb` and not just `gdb`

**Comment by BinarryCode** [comment]
same error

**Comment by headshot2017** [comment]
restart msys2 mingw x64 and try again, or try with msys2 msys

**Comment by BinarryCode** [comment]
?
![image](https://user-images.githubusercontent.com/53833277/216737354-d846bee2-83e8-4974-8ea4-2f50d7681b81.png)

**Comment by headshot2017** [comment]
maximize and show me everything

**Comment by BinarryCode** [comment]
?
![image](https://user-images.githubusercontent.com/53833277/216737678-4e5a521b-b311-44ac-9cff-0181c2cd2652.png)

**Comment by headshot2017** [comment]
check on the newest debug build on the actions tab and download the gzdoom-sm64-debug one again

if it doesn't work try launching the game from msys2 by typing `./gzdoom -iwad doom.wad`, replacing "doom.wad" with whatever WAD file you have

if that does nothing either, i'm gonna have to try and replicate this issue on another machine or a VM, but i have my doubts i can get this situation to happen because this is weird

**Comment by BinarryCode** [comment]
Works perfectly now, thanks 👍
