### ISSUE TITLE
IWad error on startup

### ISSUE THREAD

**Issue by BinarryCode** [headshot2017/gzdoom-sm64#5]
I keep getting this error on startup no matter what IWAD I use. Do I need to use a specific version of Doom/Doom2?
![image](https://user-images.githubusercontent.com/53833277/201501223-e3710a81-8d10-4ca6-b77c-bcea2a3d65a6.png)

**Comment by headshot2017** [comment]
you need to place the wad in the same folder as the gzdoom exe for it to be detected. must be ".wad" file extension as well.
alternatively try running the wad in a command prompt: ```gzdoom.exe -iwad wadname.wad```

**Comment by BinarryCode** [comment]
Okay, now it's crashing when loading maps. Do I need to send the crash report and is something like that related to OpenGL? (I will make a new issue for this if needed)

**Comment by headshot2017** [comment]
i'm not sure if these crash reports will be much help to me but go ahead
if you could use the debug build with the GDB debugger to point where it's crashing it would be better

**Comment by BinarryCode** [comment]
It seems to crash immediately when loading in Software, works fine in OpenGL but I can't really run that properly

If I were to guess, it's probably something with trying to load the model

**Comment by BinarryCode** [comment]
> It seems to crash immediately when loading in Software, works fine in OpenGL but I can't really run that properly
> 
> If I were to guess, it's probably something with trying to load the model

Also I don't know where the crash report file is on the debug release, it just crashes without giving me any specific errors

**Comment by BinarryCode** [comment]
Closing this so I can make (hopefully) actually-useful issues instead
